package main

import (
	"fmt"
	"math"
	"math/rand"
)

// PinkNoiseParams holds the parameters for generating pink noise (1/f noise).
//
// Fields:
//   Alpha    – spectral exponent (≈1.0 for pink noise, S(f) ∝ 1/f^alpha)
//   Variance – variance of the Gaussian white noise before filtering
//   Seed     – random seed for reproducibility
//
// Requisitos: 6.3, 6.4, 6.6
type PinkNoiseParams struct {
	Alpha    float64
	Variance float64
	Seed     int64
}

// GeneratePinkNoise generates exactly numBytes bytes of pink noise with
// spectral distribution S(f) ∝ 1/f^alpha.
//
// The algorithm:
//   1. Generate Gaussian white noise using Box-Muller transform
//   2. Apply 1/f filter via Voss-McCartney approximation
//   3. Clamp values to byte range [0, 255]
//
// Preconditions:
//   - params.Alpha > 0
//   - params.Variance > 0
//   - numBytes > 0
//   - numBytes <= 512 (maximum padding size per call)
//
// Postconditions:
//   - len(result) = numBytes
//   - Spectral distribution follows S(f) ∝ 1/f^alpha
//
// Returns the generated byte array and nil on success, or (nil, error) if
// preconditions are violated.
//
// Requisitos: 6.3, 6.4, 6.6
func GeneratePinkNoise(params PinkNoiseParams, numBytes int) ([]byte, error) {
	// Validate preconditions
	if params.Alpha <= 0.0 {
		return nil, fmt.Errorf("GeneratePinkNoise: alpha must be > 0, got %g", params.Alpha)
	}
	if params.Variance <= 0.0 {
		return nil, fmt.Errorf("GeneratePinkNoise: variance must be > 0, got %g", params.Variance)
	}
	if numBytes <= 0 {
		return nil, fmt.Errorf("GeneratePinkNoise: numBytes must be > 0, got %d", numBytes)
	}
	if numBytes > 512 {
		return nil, fmt.Errorf("GeneratePinkNoise: numBytes must be <= 512, got %d", numBytes)
	}

	// Initialize seeded random number generator
	rng := rand.New(rand.NewSource(params.Seed))

	// Generate Gaussian white noise using Box-Muller transform
	whiteNoise := make([]float64, numBytes)
	for i := 0; i < numBytes; i += 2 {
		// Generate two uniform random numbers in (0, 1]
		u1 := rng.Float64()
		u2 := rng.Float64()

		// Ensure u1 > 0 to avoid log(0)
		if u1 == 0.0 {
			u1 = 1e-10
		}

		// Box-Muller transform
		magnitude := math.Sqrt(-2.0*math.Log(u1)) * math.Sqrt(params.Variance)
		z0 := magnitude * math.Cos(2.0*math.Pi*u2)
		z1 := magnitude * math.Sin(2.0*math.Pi*u2)

		whiteNoise[i] = z0
		if i+1 < numBytes {
			whiteNoise[i+1] = z1
		}
	}

	// Apply 1/f filter (Voss-McCartney approximation)
	pinkNoise := applyPinkFilter(whiteNoise, params.Alpha)

	// Clamp to byte range [0, 255]
	paddingBytes := make([]byte, numBytes)
	for i := 0; i < numBytes; i++ {
		paddingBytes[i] = clampToByte(pinkNoise[i])
	}

	return paddingBytes, nil
}

// applyPinkFilter applies a 1/f^alpha filter to white noise using the
// Voss-McCartney approximation.
//
// The Voss-McCartney algorithm maintains multiple octave generators that are
// updated at different rates to approximate the 1/f spectrum.
func applyPinkFilter(whiteNoise []float64, alpha float64) []float64 {
	n := len(whiteNoise)
	if n == 0 {
		return whiteNoise
	}

	// Number of octave generators (typically 5-7 for good approximation)
	numOctaves := 7
	octaves := make([]float64, numOctaves)

	// Initialize octaves with first values
	for i := 0; i < numOctaves && i < n; i++ {
		octaves[i] = whiteNoise[i]
	}

	pinkNoise := make([]float64, n)

	// Process each sample
	for i := 0; i < n; i++ {
		// Update octaves at different rates (powers of 2)
		for j := 0; j < numOctaves; j++ {
			// Update this octave if i is divisible by 2^j
			if i%(1<<uint(j)) == 0 && i < n {
				octaves[j] = whiteNoise[i]
			}
		}

		// Sum all octaves with 1/f^alpha weighting
		sum := 0.0
		for j := 0; j < numOctaves; j++ {
			// Weight by 1/f^alpha where f is proportional to 2^j
			freq := math.Pow(2.0, float64(j))
			weight := 1.0 / math.Pow(freq, alpha)
			sum += octaves[j] * weight
		}

		// Normalize by number of octaves
		pinkNoise[i] = sum / float64(numOctaves)
	}

	return pinkNoise
}

// clampToByte clamps a float64 value to the byte range [0, 255].
func clampToByte(value float64) byte {
	// Normalize to [0, 255] range
	// Assuming input is roughly in [-3σ, +3σ] for Gaussian noise
	// Map to [0, 255] with 128 as center
	normalized := value + 128.0

	if normalized < 0.0 {
		return 0
	}
	if normalized > 255.0 {
		return 255
	}
	return byte(normalized)
}
